"""add conversation_summaries table

Revision ID: 636d779e3f1a
Revises: ff662c4e4bba
Create Date: 2026-07-11 00:50:10.850460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636d779e3f1a'
down_revision: Union[str, Sequence[str], None] = 'ff662c4e4bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_organization_id'), 'conversation_summaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_organization_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
