"""add full-text tsvector column and GIN index for hybrid retrieval

Revision ID: 7028b5cf9731
Revises: a8ed0e6510e7
Create Date: 2026-07-23 23:27:12.437114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7028b5cf9731'
down_revision: Union[str, Sequence[str], None] = 'a8ed0e6510e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_document_embeddings_content_tsv', 'document_embeddings', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_embeddings_content_tsv', table_name='document_embeddings', postgresql_using='gin')
    op.drop_column('document_embeddings', 'content_tsv')
    # ### end Alembic commands ###
